### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by AdoNunes** [AdoNunes/DiscordAlertsTrader#1]
- ~~Catch option msg exit plans~~
- ~~Catch edited msg by re-exporting messages~~
- ~~Catch edited msg where exit plan updated (ScaredShirtless)~~
- Catch msg with exit plans but no BTO|STC alert
- Add threading to:
     --  ~~update trade plans with new exit orders~~
    --~~ export discord msgs --> **Complication. inside thread, not possible to hang and wait for user input.  -> send new messages to queue and have an asynch funct to ask for user input**~~
- Add dynamic exit orders, i.e. after-hours change OCO to Lim
- Add default:
    --  exit plans or at least SL
    -- ~~buy current market price~~
- ~~Remove BTO + PT1 exit order, create exits orders after BTO filled~~

**Comment by AdoNunes** [comment]
- create option STC when share price is reached
- Change SL to buy price after first PT
-

**Comment by AdoNunes** [comment]
Make extended hours Lim STC

**Comment by AdoNunes** [comment]
add strategy SL change after x% change: SL to 5% after 10% increase BTO
add more tests to check exitplan update with new STC

**Comment by AdoNunes** [comment]
Don't STCx from alert if already sold in queued PT order

**Comment by just-rich** [comment]
@AdoNunes We have a platform that does this already on a massive scale, do you have any experience with discord.js and typescript? We've been looking for another contributor.

LMK, you can check out the app and bot here; https://tradehub.pro or https://docs.thetradehub.net

**Comment by AdoNunes** [comment]
> @AdoNunes We have a platform that does this already on a massive scale, do you have any experience with discord.js and typescript? We've been looking for another contributor.
> 
> LMK, you can check out the app and bot here; https://tradehub.pro or https://docs.thetradehub.net

Let's chat by email or discord. Tradehub looks promising! From what I can see copy trading hasn't been implemented right? Is it because of RIA license pending?
