### ISSUE TITLE
No matching distribution found for pyside2

### ISSUE THREAD

**Issue by blakeparkinson** [AdoNunes/DiscordAlertsTrader#12]
Any idea how to solve this? It seems to be a problem where PySimpleGUIQt doesn't play nicely with pyside2. I tried downgrading my condo env to 3.9 but no luck.

**Comment by AdoNunes** [comment]
is it in a windows or mac?
As far as I know, when users do a fresh env with python=3.10 (or 3.9) and install dependencies with `pip install -e .` it works fine. 
if you have pyside2 before installing pysimplegui there might be incompatibility issues

**Comment by blakeparkinson** [comment]
It's a mac. Let me blow away my env and try again!

**Comment by raxbits** [comment]
mac has issues, i could not get it going. u can try compiling from scratch.

**Comment by AdoNunes** [comment]
Yeah with Mac pip install DisocrdAlertsTrader gives problems. Better do git clone and then follow the readme.md instructions, a couple of days a mac user installed it without issues after creating a new env without old dependencies

**Comment by oleg-d** [comment]
pyside2 isn't supported on Mac M-chips. i've run into the same problem now
