### ISSUE TITLE
Needs update for averaging order. 

### ISSUE THREAD

**Issue by kbichave** [AdoNunes/DiscordAlertsTrader#13]
When BTO alerted multiple times, the alert is ignored by alerts_trader.py :
```Repeated BTO```

Also some warnings:
alerts_tracker.py:130: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.47/1.27' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  self.portfolio.loc[open_trade, "Prices"] = f"{old_price}/{order['price']}"
alerts_tracker.py:135: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.47/1.28' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  self.portfolio.loc[open_trade, "Prices-actual"] = avgs_prices_al

**Comment by AdoNunes** [comment]
The deployed version now has a config option to accept averaging down orders.
I will fix future warnings in the future :) Thanks
