### ISSUE TITLE
Discord Login Error

### ISSUE THREAD

**Issue by Ravi-099** [AdoNunes/DiscordAlertsTrader#15]
Has anybody encountered this error message before? It does launch a GUI but no data in it. 

`File "C:\Users\R\scoop\apps\miniconda3\current\lib\site-packages\discord\utils.py", line 1474, in _get_build_number
    build_url = 'https://discord.com/assets/' + re.compile(r'assets/+([a-z0-9]+)\.js').findall(login_page)[-2] + '.js'
IndexError: list index out of range`

**Comment by AdoNunes** [comment]
made an announcement a while back in the disc server. The package needs to be updated:
If you are getting an index error when starting the package run in the terminal:
`pip install git+https://github.com/pc111c/discord.py-self.git@patch-1`
it will update discord.py-self package

**Comment by Ravi-099** [comment]
Thank you that seems to fix the problem. Sorry, but I am new to this platform. Could you please answer what server I should be following to run this script?

As per the config file it's looking at these channels but I don't think I am following the correct server to fetch these channels. 

channel_IDS = {
    "analyst-alerts" : 738943464259059752,
    "cb_challenge" :  1058040359038492712,
    "combine-alerts": 1113579133868458155,
    "jr-analyst-alerts":  952916697008984154,
    "X-opt-analyst": 990331623260180580,
    "X-opt-staff": 990331641094361109,
    "X-stock-admin": 991515360509571233,
    "X-stock-staff": 991515370194227210,
    }

**Comment by AdoNunes** [comment]
remove all of these and add the channel ids that you want and have access
