### ISSUE TITLE
Will this package Run in Visual Studio Code Python 3.8?

### ISSUE THREAD

**Issue by sinsinnati** [AdoNunes/DiscordAlertsTrader#7]
Having an issue. I am using Visual Studio Code with Python 3.8. When I navigate to the DiscordAlertsTrader directory and type in the terminal: DiscordAlertsTrader

It generates the following error:

DiscordAlertsTrader : The term 'DiscordAlertsTrader' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a    
path was included, verify that the path is correct and try again.
At line:1 char:1

Thanks!

**Comment by AdoNunes** [comment]
did you do `pip install -e .` from the package folder? Are you in the correct env? in VSC try running gui.py

**Comment by sinsinnati** [comment]
Hi - thank you for responding so quickly. I did install okay. When I run gui.py it opens but a few seconds later closes here is the output in  the terminal:

gui_generator.py:29: RuntimeWarning: invalid value encountered in double_scalars
  values_s = [str(round(v, decim)) if v %1 else str(round(v)) for v in values]
2
3
4
5

then closes.

**Comment by AdoNunes** [comment]
Yeah for some reason when running yhe first times it does that. Try running
it a few times and see if it works.
If not I will reinstall it in a clean env in case some last update broke it
Let me know

**Comment by sinsinnati** [comment]
LOL I can't believe  it...that's  exactly what is was: I just re-ran gui.py a couple more times  and it launched correctly! Do you know why just typing "DiscordAlertsTrader" is an unknown command? Is it because I am using VSC? Thank  you so much for helping me figure  it out

**Comment by AdoNunes** [comment]
it is just a warning right? 
Might be a nan, but not sure why you have a nan. Could you click on update button in the portfolio tab and see if it pops up and then also in analysts portfolio tab. 

The only thing I did recently was to  set remove_zero to False:
on line 37 change remove_zero=True
```def pd_col_str_frmt(pd_Series, max_decim=2, remove_zero=False):
  ``

**Comment by sinsinnati** [comment]
It's just a warning and was wondering about it. I changed the line 37 value to True. It appears when I click on Analysts Portfolio and Analysts Stats. Maybe it's because  I no longer have these analysts in my config.ini? It does not occur when  I click  on "update" on  the "Portfolio" tab or the specific channel tab. Thanks again  for all your help...great work here.

**Comment by AdoNunes** [comment]
the warning comes from trying to reformat the numbers for the gui and probably there is a nan or inf... unless you changed the analysts' portfolio name in the config you should have the same portfolio. I usually push the portfolio at the end of the day so I have version control and also so users can see which trader to follow based on past performance

**Comment by sinsinnati** [comment]
Okay, I left the portfolio as is, but still the same. It's okay maybe a nan or inf somewhere in it. I downloaded this via the "Download" button on the <>Code section, so I'm assuming that's the latest. When do you think you will have the Webull Functionality in place? I've used Ted  Chou's github Webull API and it works well. I'm sure you checked that out. I know how to code all the order functions of it by now, as well.

**Comment by AdoNunes** [comment]
I started with the webull class but it only lets me trade during open hours, so it is a bit hard to find time. yeah also using Ted's api. Not sure how well webull will work, the package also gathers quotes from open trades every 5 sec. For now etrade seems to have cash accounts so no day trade limits for port under 25k

**Comment by sinsinnati** [comment]
Yeah, it isn't the greatest API..so limited and only during open hours. Hope it gets better asap. So are you saying that e-trade allows unlimited day trades with a cash account? I thought one had to go offshore like CMEG to do this. If I am understanding you correctly, that's awesome. Do you know if it would include e-trade pro or like real-time data / quotes etc.?

**Comment by AdoNunes** [comment]
For all I know with webull OCO is limited to a PT and SL. Day trading minimum balance is only for margin accounts, for cash accounts like webull, robin, etc there is no minimum, turns out etrade also has cash accounts and I probably opened a cash one. I ve been trading with my package and so far no issues or restrictions. Real time data is as good as TDA and also free. Many of the package users are on etrade

**Comment by sinsinnati** [comment]
I have had a TDA acct for years,  but never signed up for the API. It looks like Schwab is taking forever to open the API access back up. Have you heard of any new dates aside from what's online?  I sent you an email. Thanks again for all your help.

**Comment by AdoNunes** [comment]
awesome, thanks! I have pushed the changes.

That's the last TDA told me: "We are aiming to have our endpoint live this summer with a full release scheduled for winter of 2023."
